name: Discord

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    uses: ForgeGHActionsTestOrg/Actions/.github/workflows/discord-build-notifier.yml@main
    with:
      build_status: 'started'
      build_number: '0.0.1'
    secrets:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
