name: Publish

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    uses: ForgeGHActionsTestOrg/Actions/.github/workflows/gradle.yml@79fc31aebf258654d0cd933829bd5f53a3139f68
    with:
      java: 8
      gradle_tasks: "build"
    secrets:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
