name: Publish

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    uses: ForgeGHActionsTestOrg/Actions/.github/workflows/gradle.yml@fb8113acd689e8fbe12a13ece2aa693c7c37ac83
    with:
      java: 8
      gradle_tasks: "build"
    secrets:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
