name: Publish

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    uses: ForgeGHActionsTestOrg/ForgeSharedActions/.github/workflows/gradle.yml@main
    with:
      java: 8
      gradle_tasks: "build"
