name: Publish

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    uses: ForgeGHActionsTestOrg/Actions/.github/workflows/gradle.yml@9a05ade756c6fdccf054d8edfb2214d0c605e49b
    with:
      java: 8
      gradle_tasks: "build"
    secrets:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
