name: Publish

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    uses: ForgeGHActionsTestOrg/Actions/.github/workflows/gradle.yml@d1331d1c98f99ea0f5b9880c0d8938da11617c5f
    with:
      java: 8
      gradle_tasks: "build"
    secrets:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
